CREATE SEQUENCE SEQ_TREINO START WITH 1 INCREMENT BY 1;

CREATE TABLE TREINO (
    ID                      BIGINT          NOT NULL,
    NOME                    VARCHAR(150),
    PESO_KG                 DOUBLE PRECISION,
    SERIES                  INTEGER,
    GRUPO_MUSCULAR          VARCHAR(50),
    EXERCICIO               VARCHAR(50),
    URL_IMG_EXERCICIO       VARCHAR(500),
    URL_VIDEO_EXERCICIO     VARCHAR(500),
    TEMPO_PAUSA_SEGUNDOS    INTEGER,
    CONSTRAINT PK_TREINO PRIMARY KEY (ID)
);